### ISSUE TITLE
my desired metals features and improvements

### ISSUE THREAD

**Issue by doofin** [doofin/metals#2]
### todo:

- [ ] **exhaustive match for tuples** 
- [x] **show type only on val binding :** https://github.com/scalameta/metals/pull/5284#discussion_r1255726805
- [x] type hint is too messy at "case" and method type parameter at call site
- [x] selection expansion https://github.com/scalameta/metals/pull/4921
- [ ] auto complete word in comment 
- [ ] https://github.com/scalameta/mdoc/issues/732
- [ ] https://github.com/scalameta/metals/pull/6109
- [ ] action to add Scala doc
- [x] https://github.com/scalameta/metals-feature-requests/issues/372
- [ ] show only methods in symbols
### code action: 
- [ ] add docs
